[CN-1287]: add license secret creation step
hazelcast-guides/hazelcast-platform-operator-jet pull request #5
Opened 2024-06-26 13:18 UTC by kutluhanmetin

2024-06-27 14:33 UTC, hasancelik requested changes

2024-06-27 14:33 UTC, hasancelik commented on docs/modules/ROOT/pages/hazelcast-platform-operator-jet.adoc
Actually, Hazelcast OS is enough to submit jet job but with 5.13 release, the operator will not support OS cluster so users have to define ee license key at CR even if for OS features. So this situation might create some confusion on their side.

With the 5.13 release of Hazelcast, the operator will no longer support OS clusters. As a result, users will need to define an enterprise license key at the custom resource level, even for OS features. This change may cause confusion for some users.

Could you add a brief description to clarify this confusion?

2024-07-02 07:51 UTC, kutluhanmetin commented on docs/modules/ROOT/pages/hazelcast-platform-operator-jet.adoc
https://github.com/hazelcast-guides/hazelcast-platform-operator-jet/pull/5/commits/6d33d32b6dc2562d5989bdf1112c69cf5a1851db

2024-07-02 10:28 UTC, hasancelik approved these changes

2024-07-02 11:55 UTC, merged